export const dynamic = "force-dynamic";
import Link from "next/link";
import {TenantShell} from "@/components/tenant-shell";
import {CopyId} from "@/components/tenant/copy-id";
import {requireTenantPage} from "@/lib/auth/page-access";
import {getTenantHome} from "@/lib/db/tenant";
const money=(v:number)=>`${new Intl.NumberFormat("fr-FR").format(v)} F`;
export default async function TenantHome(){const userId=await requireTenantPage();const {profile,rentals,receipts,currentDue,summary}=await getTenantHome(userId);const current=rentals.find(r=>!r.to)??rentals[0];return <TenantShell>
  <p className="text-sm text-slate-500">{current?`${current.unit} · ${current.landlord}`:"Mon espace locataire"}</p><h1 className="text-3xl font-bold">Bonjour {profile.fullName.split(" ")[0]}</h1>
  <div className="mt-6 grid gap-5 lg:grid-cols-[1.3fr_1fr]"><section className="rounded-3xl bg-brand-blue p-6 text-white"><p className="text-sm opacity-80">Loyer en attente {currentDue?`· ${currentDue.period}`:""}</p>{currentDue?<><p className="mt-2 text-4xl font-extrabold">{money(currentDue.amount-currentDue.paid)}</p><p className="mt-4 text-sm">{money(currentDue.paid)} déjà payés · échéance {currentDue.dueOn}</p></>:<p className="mt-2 text-xl font-semibold">Aucune échéance ouverte</p>}<p className="mt-6 text-sm opacity-80">Le paiement en ligne et l’envoi de preuve seront disponibles prochainement.</p></section>
  <section className="rounded-3xl border border-brand-line bg-white p-6"><h2 className="font-bold">Mon identifiant ImmoPay</h2><p className="mt-1 text-sm text-slate-500">Votre référence personnelle.</p>{profile.immopayId?<CopyId id={profile.immopayId}/>:<p className="mt-4 text-slate-500">Aucun identifiant attribué.</p>}</section></div>
  <div className="mt-5 grid grid-cols-3 gap-3">{[[summary.total,"quittances"],[`${summary.rate}%`,"payés à temps"],[summary.rentals,"logements"]].map(([value,label])=><div key={label} className="rounded-2xl border border-brand-line bg-white p-4"><b className="block text-2xl">{value}</b><span className="text-sm text-slate-500">{label}</span></div>)}</div>
  <section className="mt-5 rounded-3xl border border-brand-line bg-white p-6"><div className="flex justify-between"><h2 className="font-bold">Dernières quittances</h2><Link href="/espace-locataire/quittances" className="text-sm font-semibold text-brand-blue">Tout voir</Link></div>{receipts.length?<ul className="mt-3 divide-y divide-slate-100">{receipts.slice(0,3).map(r=><li key={r.publicCode} className="flex justify-between gap-4 py-3"><span><b className="block capitalize">{r.period}</b><span className="text-sm text-slate-500">{money(r.amount)} · payé le {r.paidOn}</span></span><Link href={`/verify/${encodeURIComponent(r.publicCode)}`} className="text-sm font-semibold text-brand-blue">Vérifier</Link></li>)}</ul>:<p className="mt-4 text-sm text-slate-500">Aucune quittance pour le moment.</p>}</section>
</TenantShell>}
